---
title: "Covied_Test"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: cosmo
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(medicaldata)
library(tidyverse)
library(ggplot2)
library(here)
library(rsconnect)
Data <- covid_testing
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r}

T_p_Clinic <- Data %>% 
  group_by(patient_class) %>% 
  mutate(Result_T = col_rec_tat + rec_ver_tat) %>% 
  summarise(Mean=mean(Result_T))

Wtime <- ggplot(T_p_Clinic,aes(x=reorder(patient_class,Mean), y=Mean, fill= Mean))+
  geom_bar(stat= "identity")+
  theme(legend.position = "none"
        ,axis.text.x = element_text(angle = 90,size=5))+
  labs(title = "Average of Waiting Time per Patient Class",
       y="Time(Minutes)",
       x="Class")+
  coord_flip()+
  scale_fill_gradient(low="green", high = "red")
```

Column {data-width=250}
-----------------------------------------------------------------------

### Sample Size

```{r}
valueBox(dim(Data)[1])
```


### Chart B

```{r}
sliderInput("min", "Limit (minimum)", value = 50, min = 0, max = 100)

```

### Chart C

```{r}

```

Column {data-width=250}
-----------------------------------------------------------------------

### Chart C

```{r}

Positive <- Data %>% 
  group_by(result) %>% 
  summarise(n=n(),percentage=n()/nrow(Data))

Results <- ggplot(Positive, aes(x="",y=percentage, fill= result))+
  geom_col()+
  coord_polar("y", start=0)+
  theme_bw()

```

### Chart C

```{r}

```

